name: Generate contribution snake

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: Aelitonme
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%239745F5&color_dots=%23110F18,%232A1745,%234B247A,%237A3DB8,%23B57BFF
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=%23B57BFF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish generated files
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
          branch: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
